stages:
  - test
  - quality-assurance

unit_tests:
  image: golang:1.15-alpine
  stage: test
  before_script:
    - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/community build-base ffmpeg gcc libsrt-dev
  script:
    - go test -v -covermode=count -coverprofile cover.cov ./...
    - go tool cover -func=cover.cov

linters:
  image: golang:1.15-alpine
  stage: quality-assurance
  script:
    - go get -u golang.org/x/lint/golint
    - golint -min_confidence 0.3 -set_exit_status ./...
  allow_failure: true
