providers:
  docker:
    # Do not expose containers by default
    exposedbydefault: False

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  websecure:
    address: ":443"
  rtmpsecure:
    address: ":1935"

certificatesResolvers:
  mytlschallenge:
    acme:
      email: root@example.com
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

